# Generated by Django 4.2 on 2023-08-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_create_data_gin_and_object_item_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='Person'.lower(),
            options={'ordering': ['-meta__internal_id']},
        ),
    ]
